### ISSUE TITLE
qemu method starts without focus

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#36] opened 2018-07-03 11:20 UTC
the qemu method starts without focus so that when the ph2 boot is finished the user must click the mouse to gain keyboard control

**Comment by shreyanshk** [comment] 2018-07-03 11:50
I am unable to follow. Do you mean to say that keyboard gets locked for some reason?

**Comment by atrent** [comment] 2018-07-03 12:00
when you launch qemu the keyboard focus is not in the guest window, so you get the X cursor floating but if you type something nothing happens (actually I believe the characters are sent to the host window but I did not check), you have to click once with the mouse inside the guest window (that is full screen, I know) to make the keyboard work (i.e., the guest gains focus)

**Comment by shreyanshk** [comment] 2018-07-04 09:55
I cannot reproduce it (due to VBox already requiring clicking window to change focus. So, maybe that action causes focus to change already)

I've tried to fix it by using xdotool (https://www.semicomplete.com/projects/xdotool/) to shift focus.
The commits are in the fix36 branch (along with new ph1 rootfs).
Can you please try with that branch and confirm if the fix works.

**Comment by shreyanshk** [comment] 2018-07-07 08:11
@atrent , Did you try the other branch? Please let me know if the fix works.

**Comment by atrent** [comment] 2018-07-07 08:21
trying now, it does not boot any OS, I'm taking a video, give some time

**Comment by atrent** [comment] 2018-07-07 08:50
![filename00282](https://user-images.githubusercontent.com/412584/42408978-937531e0-81d3-11e8-815c-f3210007039f.png)

fatal server error (on X)

**Comment by shreyanshk** [comment] 2018-07-07 08:52
What does the line below "Fatal server error:" reads?

**Comment by atrent** [comment] 2018-07-07 08:54
no screens found

**Comment by shreyanshk** [comment] 2018-07-07 08:55
Driver for the video card was not found.
Did BootTorrent previously work on this machine?

**Comment by atrent** [comment] 2018-07-07 08:56
yes, it's the same machine I used since the beginning of tests

**Comment by shreyanshk** [comment] 2018-07-07 09:05
Since it worked previously, the drivers should be there. As, I've only added more programs to rootfs, not removed anything (in the fix36 branch).
The drivers can only be missing in the dev branch (after the slimming of rootfs).
In other words, missing drivers with fix36 branch isn't making much sense to me. Since, it worked previously and I haven't removed anything (of course, discounting bugs in SliTaz system).

What video card is present on that computer?
Does the current dev branch works correctly?

**Comment by atrent** [comment] 2018-07-07 09:17
I'm using dev, should I use fix36?

**Comment by shreyanshk** [comment] 2018-07-07 09:20
> I'm using dev, should I use fix36?

Yes! Use ``fix36``.
It'll be merged only if the fixes work.

Meanwhile, what GPU is present on this machine? Let's identify it's drivers.

**Comment by atrent** [comment] 2018-07-07 09:35
- the pc is this one: https://www.asus.com/Laptops/ASUSAutomobili_Lamborghini_VX7SX/ (NVIDIA® GeForce® GTX 560M graphics with 3GB GDDR5 video memory), but I think we should include all xorg video drivers to be safe

- the dev branch does not work now, it worked before, I'm checking out the fix36 (and pip uninstalling and reinstalling)

**Comment by atrent** [comment] 2018-07-07 11:42
fix36 boots
(but the tui does not highlight the default choice, correct?)

**Comment by shreyanshk** [comment] 2018-07-07 12:53
Does this fix the focus issue?

Also, highlight correction is not in that repo. (fix36 was made before this fix)

**Comment by atrent** [comment] 2018-07-07 13:29
focus issue seems fixed, I'm switching back to dev

**Comment by shreyanshk** [comment] 2018-07-07 13:31
Okay, I'll add this fix to dev branch.

**Comment by shreyanshk** [comment] 2018-07-07 16:33
I've added drivers for nvidia, amd gpus and added the focus fix to ``dev`` branch.
I've also added the kvm drivers to same branch ``dev``.
Please check if:
* the new gpu drivers work for this computer
* window focusing is working
* KVM is working

**Comment by atrent** [comment] 2018-07-08 16:21
better to add all video drivers

**Comment by shreyanshk** [comment] 2018-07-08 16:40
Drivers are going to be little bit of trial and error.

Also, I see that Kernel Modesetting was detected by X. That means graphics should work.
can you check if perhaps X was activated on another console? Because KMS is the recommended way for many GPUs.

**Comment by shreyanshk** [comment] 2018-07-10 13:37
@atrent ,
Can you try the new ``videofix`` branch and check if the new image works with your computer?
I'll merge it into the ``dev`` branch if it works.
I've added another package named ``xorg-xf86-video-modesetting`` to the image.

**Comment by atrent** [comment] 2018-07-12 06:16
tried (I mean: pulled --all, checkout videofix, pip uninstall and then pip install, correct?)
it does not work on one machine:
![2018-07-12 08 09 16](https://user-images.githubusercontent.com/412584/42615731-c5031656-85ab-11e8-9333-d2de1dc79171.jpg)


let's leave this issue open and concentrate on packaging

i.e., revert to the original slitaz image

we'll think about it later

**Comment by shreyanshk** [comment] 2018-07-12 08:18
I've reverted the image to the previous version and added KVM modules to the image in commit e5837981722d72f5a2760c204fce375f037e49d0
The new image is in the ``dev`` branch.
Please consider trying this image and checking if there things also work for you:

*    display work for this computer
*    window focusing is working
*    KVM is working
*    highlighting is working

**Comment by atrent** [comment] 2018-07-12 08:50
everything works except for the kvm
I've launched qemu from prompt with enable-kvm and:
"Could not access KVM kernel module: No such file or directory"

**Comment by atrent** [comment] 2018-07-12 09:12
KVM: I've found why...

cpus on VX6 (on my client1) and on Samsung R60 (client2) do NOT support kvm!
(no vmx in /proc/cpuinfo flags)

sorry, my fault, I did not notice before

**Comment by shreyanshk** [comment] 2018-07-12 13:30
Nice!, it's progress as the cause has been identified.
I think the repo tree as of commit df4dbc2625affb06d8812c03b59ef180b007635e worked correctly.
Please consider trying the code at that commit.
I think we may not need to revert commit 431548c45d37786723582bdc50da06870541ea50 and maybe able to include an optimal minimal image.

**Closed** 2018-08-27 05:39 UTC
