### ISSUE TITLE
killing qemu "shuts down" the whole machine

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#38] opened 2018-07-03 11:25 UTC
I've noticed that killing the qemu process "shuts down" (actually, the screen goes blank instantly, keyboard is useless and the only option is the power switch) the machine.

It may be more useful if, e.g., the tui could re-gain control?

**Comment by shreyanshk** [comment] 2018-07-03 12:04
I'm aware of it.
Closing only qemu kills the whole display stack but closing Xorg (kill -9 $(pidof Xorg)) doesn't.
I can reproduce it but, unfortunately, I can't see how to debug it since no form of output works (including other ttys).
It's a bug in SliTaz's system and without output, it's not possible to debug.

**Comment by shreyanshk** [comment] 2018-07-07 12:56
Have no idea on how to fix this without display.

Only way I can see is that somehow I'll have to put an SSH server on the client image and then hope for some error messages in the console.

**Comment by atrent** [comment] 2018-07-07 13:17
then leave this issue open, it's already marked as "low pri"

**Comment by shreyanshk** [comment] 2018-08-10 07:03
I was able to identify that the cause of the error is a segfault in libX11.so

I figured that SliTaz is including a nice web based configuration interface (including a webbased terminal) with it called TazPanel.

To activate TazPanel, do the following:
1) open shell on client
2) kill process httpd (kill -9 <pid of /usr/sbin/httpd>)
3) edit /etc/slitaz/httpd.conf and comment out the Deny address section + allow all in Allow address section
```
# Deny addresses
# D:*
# Allow addresses
A:*
```
4) restart TazPanel
```
/usr/sbin/httpd -p 82 -u root -c /etc/slitaz/httpd.conf -r TazPanel Authentication - Default: root:root
```
5) visit port 82 of the client from any browser and access the web terminal to get the logs

The relevant line from dmesg is
```
qemu-system-x86[2664]: segfault at 4d0 ip b688a9da sp bfe78220 error 4 in libX11.so.6.3.0[b685a000+118000]
```

**Comment by atrent** [comment] 2018-08-11 13:30
could you edit the httpd.conf in ph1 image so that the httpd is always open to "*" ?

**Closed** 2018-08-13 15:15 UTC
Labels: low pri

**Comment by shreyanshk** [comment] 2018-08-13 15:25
Docs updated on commit 0709c2900b8a13b2815799e5f8c2dbf76d8fb4a0
